---
title: "Sherven_Tyler_Lab3"
author: "Tyler Sherven"
date: "10/3/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


###Question 1

```{r}
library(MASS)
df <- Cars93
set.seed(960)
y <- sample(1:nrow(df),40)

trainer <- df[y, ]
testy <- df[-y,]

write.csv(trainer,file = "trainee")
write.csv(testy, file = "testy")

sum(trainer$Origin == "USA")
sum(trainer$Origin == "non-USA")
```

###Question 2

```{r}
babys <- sample(c("Boy", "Girl"), size = 10, replace = TRUE, prob = c(0.515, 0.485))
table(babys)
bigbabys <- sample(c("Boy", "Girl"), size = 10000, replace = TRUE, prob = c(0.515, 0.485))
```

###Question 3

```{r}
dbinom(3, size = 10, prob=0.515)

a <- 10
b <- 0:a
c <- dbinom(b, size = a, prob = 0.515)
plot(b,c)

pbinom(8, size = 10, prob=0.515, lower.tail = FALSE)

f <- 10
g <- 0:f
h <- pbinom(g,size=f,prob=0.515)
plot(g,h)

```

###Question4 

```{r}
dbinom(4, size=10, prob=0.5)
pbinom(5, size = 10, prob = 0.5, lower.tail = FALSE)

n <- 0:20
m <- dbinom(n, size = 10, prob = 0.5)
plot(n,m)

```

